baseURL: 'http://mzee1000.io/'
languageCode: en-us
title: Mohammed Zeeshan Ahmed's Blog
theme: hugo-coder
defaultcontentlanguage: en
paginate: 20
disqusShortname: mzee1000-io
enableEmoji: true
pygmentsstyle: bw
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pluralizeListTitles: false
preserveTaxonomyNames: true
params:
    author: Mohammed Zeeshan Ahmed
    description: >-
        Just a random blog for random stuff, mostly tech-related. Opinions
        expressed are mine.
    avatarurl: 'https://github.com/mohammedzee1000.png'
    motto: 'A keen maker, programmer, engineer, sysadmin and FOSS enthusiast.'
    keywords: 'blog,developer,personal'
    info:
        - Software Engineer
        - Devops
        - Programmer
    favicon: /img/defaultFav.ico
    twitterEmoji: true
    since: 2019
    dateFormat: 'January 2, 2006'
    colorScheme: auto
    social:
        -
            name: Github
            icon: fa fa-github fa-2x
            weight: 1
            url: 'https://github.com/mohammedzee1000/'
        -
            name: Twitter
            icon: fa fa-twitter fa-2x
            weight: 2
            url: 'https://twitter.com/zee_10000/'
        -
            name: LinkedIn
            icon: fa fa-2x fa-linkedin
            weight: 3
            url: 'https://www.linkedin.com/in/mohammedzee1000/'
taxonomies:
    category: categories
    series: series
    tag: tags
    author: authors
menu:
    main:
        -
            name: About
            weight: 1
            url: about/
        -
            name: Blog
            weight: 2
            url: posts/

