baseURL = "http://mzee1000.io/"
languageCode = "en-us"
title = "Mohammed Zeeshan Ahmed's Blog"
theme = "hugo-coder"
defaultcontentlanguage = "en"
paginate = 20
disqusShortname = "mzee1000-io"
#Enable Hugo Emoji Conversion
enableEmoji=true
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	author = "Mohammed Zeeshan Ahmed"
	description = "Just a random blog for random stuff, mostly tech-related. Opinions expressed are mine."
	avatarurl = "https://github.com/mohammedzee1000.png"
	motto = "A keen maker, programmer, engineer, sysadmin and FOSS enthusiast."
	keywords = "blog,developer,personal"
	info = ["Software Engineer", "Devops", "Programmer"]
	favicon = "/img/defaultFav.ico"

	#Enable Twitter Emoji
	twitterEmoji=true
	since = 2019
	dateFormat = "January 2, 2006"
	colorScheme = "auto"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"


# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/mohammedzee1000/"
#[[params.social]]
#  name = "Gitlab"
#  icon = "fa fa-gitlab fa-2x"
#  weight = 2
#  url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/zee_10000/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/mohammedzee1000/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
