baseURL: "https://mzee1000.io/"
languageCode: en-us
title: "Mohammed Zeeshan Ahmed's Blog"
defaultContentLanguage: en
pagination:
  pagerSize: 20
enableEmoji: true
enableRobotsTXT: true
pluralizeListTitles: false
preserveTaxonomyNames: true
canonifyURLs: true

# Modules
module:
  imports:
    - path: github.com/panr/hugo-theme-terminal

# Markdown & code highlighting (Chroma)
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: bw
    guessSyntax: true
    lineNos: false

services:
  disqus:
    shortname: mzee1000-io

# -------- Terminal theme params --------
params:
  # Site identity
  title: "Mohammed Zeeshan Ahmed"
  subtitle: "A keen maker, programmer, engineer, sysadmin and FOSS enthusiast."
  description: >
    Just a random blog for random stuff, mostly tech-related. Opinions expressed are mine.

  # Theme look & layout
  centerTheme: false      # center main column
  fullWidthTheme: false  # set true for wide layout
  favicon: "/images/favicon.png"
  enableGitInfo: true

  # Content/UX
  readingTime: true
  toc: true               # per-post ToC (works if your content has headings)
  dateFormat: "January 2, 2006"

  # Footer/copyright (optional)
  #footerCopyright: "© 2019–present Mohammed Zeeshan Ahmed"
  footerCopyright: "2019–present Mohammed Zeeshan Ahmed"

  # Social links shown in header/footer (Terminal supports simple icon names; FA works if theme has it)
  social:
    - name: Email
      url: "mailto:mohammed.zee1000@gmail.com"
      icon: "envelope"
    - name: GitHub
      url: "https://github.com/mohammedzee1000/"
      icon: "github"
    - name: Twitter
      url: "https://twitter.com/zee_10000/"
      icon: "twitter"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/mohammedzee1000/"
      icon: "linkedin"

  # Extra meta
  author: "Mohammed Zeeshan Ahmed"
  since: 2019
  avatarurl: "https://github.com/mohammedzee1000.png"

taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors

menu:
  main:
    - name: About
      weight: 1
      url: "/about/"
    - name: Blog
      weight: 2
      url: "/posts/"

