#!/usr/bin/env bash

echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"

# Build the project.
hugo # if using a theme, replace with `hugo -t <YOURTHEME>`

# Copy cname
cp -avrf CNAME public/

# reclone the website
rm -rf /tmp/mysite
git clone git@github.com:mohammedzee1000/mohammedzee1000.github.io.git /tmp/mysite

# update content in site after removing what is there
rm -rf /tmp/mysite/*
cp -avrf public/* /tmp/mysite/

pushd /tmp/mysite
git add .
git commit -sm "Updating site content"
git push
popd
rm -rf public
